{"level":"error","ts":1630590739.485743,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithError: ERROR: duplicate key value violates unique constraint \"users_email_key\" (SQLSTATE 23505)","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users","request_method":"POST","response_code":400,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:17\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:27\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).create\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:71\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"info","ts":1630590861.7144213,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-service-template","app-version":"1.0.0"}
{"level":"error","ts":1630591502.6603389,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithError: ERROR: duplicate key value violates unique constraint \"users_email_key\" (SQLSTATE 23505)","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users","request_method":"POST","response_code":400,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:17\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:27\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).create\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:71\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"error","ts":1630591506.058264,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithError: ERROR: duplicate key value violates unique constraint \"users_email_key\" (SQLSTATE 23505)","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users","request_method":"POST","response_code":400,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:17\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:27\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).create\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:71\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"error","ts":1630591509.9048824,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithValidationError: Key: 'User.Email' Error:Field validation for 'Email' failed on the 'email' tag","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users","request_method":"POST","response_code":422,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:17\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithValidationError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:32\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).create\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:65\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"error","ts":1630591512.6487093,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithError: error: conflicting key 'required' rule 'Unknown' with text '{0} is a required field' for locale 'en', value being ignored","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users","request_method":"POST","response_code":400,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:17\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:27\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).create\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:71\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"info","ts":1630591758.653093,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-service-template","app-version":"1.0.0"}
{"level":"error","ts":1630591777.2383244,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithValidationError: Key: 'User.Email' Error:Field validation for 'Email' failed on the 'email' tag","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users","request_method":"POST","response_code":422,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:17\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithValidationError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:32\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).create\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:65\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"error","ts":1630591783.0239902,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithValidationError: Key: 'User.Password' Error:Field validation for 'Password' failed on the 'gte' tag","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users","request_method":"POST","response_code":422,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:17\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithValidationError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:32\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).create\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:65\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"error","ts":1630591786.3076618,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithValidationError: Key: 'User.Password' Error:Field validation for 'Password' failed on the 'gte' tag","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users","request_method":"POST","response_code":422,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:17\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithValidationError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:32\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).create\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:65\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"error","ts":1630591792.1614673,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithError: ERROR: duplicate key value violates unique constraint \"users_email_key\" (SQLSTATE 23505)","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users","request_method":"POST","response_code":400,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:17\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:27\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).create\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:71\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"info","ts":1630593594.1054864,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-service-template","app-version":"1.0.0"}
{"level":"error","ts":1630593656.490676,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithError: ERROR: duplicate key value violates unique constraint \"users_email_key\" (SQLSTATE 23505)","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users","request_method":"POST","response_code":400,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:17\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:27\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).create\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"error","ts":1630593661.6696572,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithValidationError: Key: 'User.Email' Error:Field validation for 'Email' failed on the 'email' tag","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users","request_method":"POST","response_code":422,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:17\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithValidationError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:32\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).create\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:94\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"error","ts":1630593666.400643,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithValidationError: Key: 'User.Email' Error:Field validation for 'Email' failed on the 'email' tag\nKey: 'User.Password' Error:Field validation for 'Password' failed on the 'gte' tag","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users","request_method":"POST","response_code":422,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:17\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithValidationError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:32\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).create\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:94\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"info","ts":1630594673.716998,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-service-template","app-version":"1.0.0"}
{"level":"info","ts":1630600793.0734444,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-service-template","app-version":"1.0.0"}
{"level":"info","ts":1630600995.4037638,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-service-template","app-version":"1.0.0"}
{"level":"info","ts":1630601193.7931495,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-service-template","app-version":"1.0.0"}
{"level":"info","ts":1630601208.9575188,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-service-template","app-version":"1.0.0"}
{"level":"info","ts":1630601251.5852199,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-service-template","app-version":"1.0.0"}
{"level":"info","ts":1630601478.1077683,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-service-template","app-version":"1.0.0"}
{"level":"info","ts":1630601503.036416,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-service-template","app-version":"1.0.0"}
{"level":"error","ts":1630601511.226942,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithError: no rows in result set","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users/:id","request_method":"DELETE","response_code":400,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:17\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:27\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).archive\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:153\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"error","ts":1630601513.965857,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithError: no rows in result set","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users/:id","request_method":"DELETE","response_code":400,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:17\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:27\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).archive\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:153\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"error","ts":1630601526.3958955,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithError: Key: 'archiveUserRequest.Password' Error:Field validation for 'Password' failed on the 'required' tag","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users/:id","request_method":"DELETE","response_code":400,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:17\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:27\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).archive\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:133\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"info","ts":1630601749.1218016,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-service-template","app-version":"1.0.0"}
{"level":"error","ts":1630601756.0005574,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithError: Key: 'archiveUserRequest.Password' Error:Field validation for 'Password' failed on the 'required' tag","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users/:id","request_method":"DELETE","response_code":400,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:17\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:27\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).archive\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:133\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"error","ts":1630601770.0952425,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithError: no rows in result set","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users/:id","request_method":"DELETE","response_code":400,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:17\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:27\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).archive\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:153\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"info","ts":1630601889.1636379,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-service-template","app-version":"1.0.0"}
{"level":"error","ts":1630601900.2441826,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithError: no rows in result set","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users/:id","request_method":"DELETE","response_code":400,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:17\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:27\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).archive\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:153\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"info","ts":1630601918.2346687,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-service-template","app-version":"1.0.0"}
{"level":"info","ts":1630602033.0648863,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-service-template","app-version":"1.0.0"}
{"level":"error","ts":1630602039.1607869,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithError: user with given id not found.","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users/:id","request_method":"DELETE","response_code":400,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:17\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:27\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).archive\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:153\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"info","ts":1630602202.1143544,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-service-template","app-version":"1.0.0"}
{"level":"error","ts":1630602212.9103131,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithError: user with id 1 not found.","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users/:id","request_method":"DELETE","response_code":400,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:17\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:27\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).archive\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:153\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"info","ts":1630602226.2302856,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-service-template","app-version":"1.0.0"}
{"level":"error","ts":1630602377.917893,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithError: ERROR: duplicate key value violates unique constraint \"users_email_key\" (SQLSTATE 23505)","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users","request_method":"POST","response_code":400,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:17\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:27\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).create\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:109\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"error","ts":1630602384.3470514,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithValidationError: Key: 'User.Email' Error:Field validation for 'Email' failed on the 'email' tag","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users","request_method":"POST","response_code":422,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:17\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithValidationError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:32\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).create\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:104\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"error","ts":1630602511.706096,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithError: incorrect password","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users/:id","request_method":"DELETE","response_code":400,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:17\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:27\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).archive\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:153\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"info","ts":1630602668.6446605,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-service-template","app-version":"1.0.0"}
