{"level":"info","ts":1631026598.1203365,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-service-template","app-version":"1.0.0"}
{"level":"info","ts":1631026620.06428,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-service-template","app-version":"1.0.0"}
{"level":"info","ts":1631026630.0003116,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-service-template","app-version":"1.0.0"}
{"level":"error","ts":1631026651.2411978,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithError: no rows in result set","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users/:id","request_method":"GET","response_code":400,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:18\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:28\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).getByID\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:146\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"info","ts":1631026711.5795639,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-service-template","app-version":"1.0.0"}
{"level":"error","ts":1631026714.3454037,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithError: user with id 2 not found","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users/:id","request_method":"GET","response_code":400,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:18\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:28\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).getByID\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:146\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"info","ts":1631026929.64994,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-service-template","app-version":"1.0.0"}
{"level":"error","ts":1631026937.7717514,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithError: user with id 2 not found","app-name":"go-service-template","app-version":"1.0.0","path":"/api/v1/users/:id","request_method":"GET","response_code":400,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:18\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:28\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).getByID\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:146\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"info","ts":1631027037.325214,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-service-template","app-version":"1.0.0"}
{"level":"info","ts":1631027066.73734,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-auth-service","app-version":"1.0.0"}
{"level":"info","ts":1631027236.7146356,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-auth-service","app-version":"1.0.0"}
{"level":"info","ts":1631027289.120239,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-auth-service","app-version":"1.0.0"}
{"level":"info","ts":1631027614.5318978,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-auth-service","app-version":"1.0.0"}
{"level":"info","ts":1631027738.6133437,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-auth-service","app-version":"1.0.0"}
{"level":"error","ts":1631027742.186545,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithError: archived user with id 1 not found","app-name":"go-auth-service","app-version":"1.0.0","path":"/api/v1/users/:id/archive","request_method":"PATCH","response_code":400,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:18\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:28\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).archive\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:85\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"error","ts":1631027759.8089597,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithValidationError: Key: 'ArchiveUserRequest.IsArchive' Error:Field validation for 'IsArchive' failed on the 'required' tag","app-name":"go-auth-service","app-version":"1.0.0","path":"/api/v1/users/:id/archive","request_method":"PATCH","response_code":422,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:18\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithValidationError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:33\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.ValidDTO\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/validation.go:84\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).archive\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:80\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"info","ts":1631027788.157598,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-auth-service","app-version":"1.0.0"}
{"level":"error","ts":1631027839.7363188,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithError: provide at least one field to update resource partially","app-name":"go-auth-service","app-version":"1.0.0","path":"/api/v1/users/:id","request_method":"PATCH","response_code":400,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:18\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:28\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).update\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:122\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"info","ts":1631027986.0432816,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-auth-service","app-version":"1.0.0"}
{"level":"error","ts":1631027992.4170017,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithError: user with email user@mail.com already exists","app-name":"go-auth-service","app-version":"1.0.0","path":"/api/v1/users","request_method":"POST","response_code":400,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:18\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:28\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).signUp\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:50\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"info","ts":1631028061.0599327,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-auth-service","app-version":"1.0.0"}
{"level":"error","ts":1631028071.3286786,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithError: user with email user1@mail.com already exists","app-name":"go-auth-service","app-version":"1.0.0","path":"/api/v1/users","request_method":"POST","response_code":400,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:18\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:28\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).signUp\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:50\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"error","ts":1631028149.4987814,"caller":"logger/logger.go:62","msg":"http - v1 - abortWithError: user with email user1@2mail.com already exists","app-name":"go-auth-service","app-version":"1.0.0","path":"/api/v1/users","request_method":"POST","response_code":400,"stacktrace":"github.com/ysomad/go-auth-service/pkg/logger.(*logger).error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:62\ngithub.com/ysomad/go-auth-service/pkg/logger.Error\n\t/home/alex/code/my/go-auth-service/pkg/logger/logger.go:31\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.logError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:18\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.abortWithError\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/error.go:28\ngithub.com/ysomad/go-auth-service/internal/delivery/http/v1.(*userRoutes).signUp\n\t/home/alex/code/my/go-auth-service/internal/delivery/http/v1/user.go:50\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/alex/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/snap/go/8172/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/snap/go/8172/src/net/http/server.go:1929"}
{"level":"info","ts":1631028175.6652744,"caller":"logger/logger.go:50","msg":"app - Run - signal: interrupt","app-name":"go-auth-service","app-version":"1.0.0"}
